# spring.datasource.url=jdbc:mysql://localhost:3306/essay_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
# spring.datasource.username=root
# spring.datasource.password=root1234
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# spring.datasource.url=jdbc:mysql://localhost:3306/essaydb
# spring.datasource.username=root
# spring.datasource.password=

spring.datasource.url=jdbc:mysql://mysql:3306/user
spring.datasource.username=root
spring.datasource.password=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect


# spring.jpa.hibernate.ddl-auto=update


# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect



cloudinary.cloud_name=dptbmikjg
cloudinary.api_key=753994999189293
cloudinary.api_secret=EkoatRvOdXwC7-37gGr5MHVO_Rg

spring.data.redis.host=redis-19630.c14.us-east-1-2.ec2.cloud.redislabs.com
spring.data.redis.port=19630
spring.data.redis.password=HWOZkDsvSv5Jx5vSbws6XFFuFR1wSxpQ

aws.accessKey=AKIA52HJ33W3VW6M2D74
aws.secretKey=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
aws.region=eu-north-1
aws.s3.bucketName=essay-db-949678235063-eu-north-1-an


ai.model.url=http://44.219.235.144/docs
